### ISSUE TITLE
Graphable Output format

### ISSUE THREAD

**Issue by loog** [vacri/timeconnect#2]
It is good that there is a tool to convert timeconnect log files into a format that can be easily graphed, however this process takes a while and adds an extra step to my workflow.

It would be nice if there was a way to tell timeconnect to simply output a format that was easy to graph.  This could also add some information that is simply missing from the current output too - like a cumulative/delta count for sent/recv/failed.  Right now the only way to get that information is right at the end, which makes it hard to graph.

When I say this conversion takes a while, I had a timeconnect session log from a three day period - just under 17Meg of log data, with 257k lines - and running timeconnect2tsv took over 2m50s!

**Comment by vacri** [comment]
The --tsv flag has now been added, and this changes the output to a text-free tab-separated series of columns: timestamp, elapsed time, number of attempts, number of successful returns, fail code (0 on successful return)

Both the elapsed time and the fail code columns will report -1 if there's a local socket error and -2 if there's a connect error
